Add regenerator-runtime to jest setup files
After upgrading to jest 24.0.0, the test suite failed to run with the
following error:

  ReferenceError: regeneratorRuntime is not defined

This fix was proposed here:

  https://github.com/facebook/jest/issues/5698